# Generated by Django 5.0.1 on 2024-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('numsocio', models.IntegerField(max_length=15)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
    ]
