# Generated by Django 5.0.1 on 2024-02-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='DNI',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numsocio',
            field=models.IntegerField(),
        ),
    ]
